// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiuUHzFI4JXVy5YTTEkJUGEYOaoiNRgE4',
    appId: '1:952033133349:web:18bd9503f8796ae7d910cc',
    messagingSenderId: '952033133349',
    projectId: 'sample-app-e0f49',
    authDomain: 'sample-app-e0f49.firebaseapp.com',
    storageBucket: 'sample-app-e0f49.firebasestorage.app',
    measurementId: 'G-SQFVKSK3F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHtS5fd9LlOt9RjN0T_JIHSPNmQVMfpN0',
    appId: '1:952033133349:android:acefb1d23822e92cd910cc',
    messagingSenderId: '952033133349',
    projectId: 'sample-app-e0f49',
    storageBucket: 'sample-app-e0f49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwuJTgqU0Xra7ULT0AhV_S8_02HC5ys4c',
    appId: '1:952033133349:ios:a8b69d4ecc4fa6aad910cc',
    messagingSenderId: '952033133349',
    projectId: 'sample-app-e0f49',
    storageBucket: 'sample-app-e0f49.firebasestorage.app',
    iosBundleId: 'com.example.sampleapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwuJTgqU0Xra7ULT0AhV_S8_02HC5ys4c',
    appId: '1:952033133349:ios:a8b69d4ecc4fa6aad910cc',
    messagingSenderId: '952033133349',
    projectId: 'sample-app-e0f49',
    storageBucket: 'sample-app-e0f49.firebasestorage.app',
    iosBundleId: 'com.example.sampleapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiuUHzFI4JXVy5YTTEkJUGEYOaoiNRgE4',
    appId: '1:952033133349:web:3c57166a386f3a8cd910cc',
    messagingSenderId: '952033133349',
    projectId: 'sample-app-e0f49',
    authDomain: 'sample-app-e0f49.firebaseapp.com',
    storageBucket: 'sample-app-e0f49.firebasestorage.app',
    measurementId: 'G-3PSE5RY98D',
  );
}
